#!/usr/bin/env python
import os
import sys
from subprocess import check_call, Popen, PIPE

_dname = os.path.dirname

REPO_ROOT = _dname(_dname(_dname(os.path.abspath(__file__))))
os.chdir(REPO_ROOT)


def run(command):
    return check_call(command, shell=True)


try:
    python_version = os.environ['PYTHON_VERSION']
except KeyError:
    python_version = '.'.join([str(i) for i in sys.version_info[:2]])

p = Popen(['pip', 'uninstall', '-y', 'awsebcli'], stdout=PIPE)
p.communicate()

run('pip install .')
run('pip install -r dev_requirements.txt')
