#!/usr/bin/env python
# Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
# http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
import os
import sys
from subprocess import check_call, Popen, PIPE

_dname = os.path.dirname

REPO_ROOT = _dname(_dname(_dname(os.path.abspath(__file__))))
os.chdir(REPO_ROOT)


def run(command):
    return check_call(command, shell=True)


try:
    python_version = os.environ['PYTHON_VERSION']
except KeyError:
    python_version = '.'.join([str(i) for i in sys.version_info[:2]])

p = Popen(['pip', 'uninstall', '-y', 'awsebcli'], stdout=PIPE)
p.communicate()

run('pip install . --no-cache-dir')
run('pip install -r dev_requirements.txt --no-cache-dir')
